package booker.BookingApp.enums;

public enum Privilege {
    VIEW_ACCOMMODATIONS,
    UPDATE_ACCOMMODATION,
    CREATE_ACCOMMODATION,
    ACCOUNT_MANAGEMENT,
    DELETE_ACCOUNT,
    DEFINE_AVAILABILITY,
    APPROVE_ACCOMMODATION,
    SEARCH_ACCOMMODATIONS,
    VIEW_ACCOMMODATION_DETAILS,
    REQUEST_RESERVATION,
    DEFINE_CONFIRMATION_METHOD,
    VIEW_REQUESTS,
    DELETE_REQUEST,
    APPROVE_REQUEST,
    CANCEL_RESERVATION,
    COMMENT_OWNER,
    REPORT_COMMENT,
    COMMENT_ACCOMMODATION,
    APPROVE_COMMENT,
    NOTIFICATIONS,
    REPORT_USER,
    BLOCK_USER,
    REPORTS,
    FAVOURITE_ACCOMMODATIONS,
    CONFIRM_RESERVATION,
    HELLO_GUEST,
    HELLO_OWNER,
    HELLO_ADMIN

}
